all:
	pdflatex lecture
	pdflatex lecture
	@echo "pdftk A=lecture.pdf cat A1-7 output info.pdf"
	@echo "pdftk A=lecture.pdf cat A8-27 output week01.pdf"
	@echo "pdftk A=lecture.pdf cat A28-41 output week02.pdf"
	@echo "pdftk A=lecture.pdf cat A42-57 output week03.pdf"
	@echo "pdftk A=lecture.pdf cat A58-69 output week04.pdf"
