all:
	pdflatex lecture
	pdflatex lecture
	@echo "pdftk A=lecture.pdf cat A1-7 output info.pdf"
	@echo "pdftk A=lecture.pdf cat A8-27 output week01.pdf"
	@echo "pdftk A=lecture.pdf cat A28-41 output week02.pdf"
	@echo "pdftk A=lecture.pdf cat A42-57 output week03.pdf"
	@echo "pdftk A=lecture.pdf cat A58-69 output week04.pdf"
	@echo "pdftk A=lecture.pdf cat A70-81 output week05.pdf"
	@echo "pdftk A=lecture.pdf cat A82-91 output week06.pdf"
	@echo "pdftk A=lecture.pdf cat A92-102 output week07.pdf"
	@echo "pdftk A=lecture.pdf cat A103-112 output week08.pdf"
	@echo "pdftk A=lecture.pdf cat A113-121 output week09.pdf"
	@echo "pdftk A=lecture.pdf cat A122-137 output week10.pdf"
	@echo "pdftk A=lecture.pdf cat A138-148 output week11.pdf"
