all:
	pdflatex homework2_sol
	pdflatex homework2_sol

hw1:
	pdflatex homework1
	pdflatex homework1

hw2:
	pdflatex homework2
	pdflatex homework2

sol1:
	pdflatex homework1_sol
	pdflatex homework1_sol

sol2:
	pdflatex homework2_sol
	pdflatex homework2_sol
