all:
	pdflatex extra_fugacity
	pdflatex extra_fugacity

cycle:
	pdflatex extra_cycle
	pdflatex extra_cycle

dalton:
	pdflatex extra_dalton
	pdflatex extra_dalton

dice:
	pdflatex extra_dice
	pdflatex extra_dice

fugacity:
	pdflatex extra_fugacity
	pdflatex extra_fugacity

walk:
	pdflatex extra_walk
	pdflatex extra_walk
