all:
	pdflatex part2_sol
	pdflatex part2_sol

part1:
	pdflatex part1
	pdflatex part1

part2:
	pdflatex part2
	pdflatex part2

sol1:
	pdflatex part1_sol
	pdflatex part1_sol

sol2:
	pdflatex part2_sol
	pdflatex part2_sol
